### ISSUE TITLE
download fail

### ISSUE THREAD

**Issue by phwaleed2024** [glomatico/spotify-web-downloader#67] opened 2024-08-21 18:51 UTC
hi i got download fail message with error
previously it worked ok
i did not change any thing and my account is premium

**Comment by joeyboli** [comment] 2024-08-22 08:08
same here most songs fail to download.

**Comment by grebt** [comment] 2024-08-22 21:24
Hi, same for me.
I executed the script with --print-exceptions option and faced following exception message:

> lib/python3.11/site-packages/spotify_web_downloader/spotify_api.py", line 74, in _check_response
    raise Exception(
Exception: Request failed with status code 403: 
[INFO     23:19:37] (Track 3/40 from URL 1/1) Downloading "044 - Monster in Rocky Beach - Teil 03"

It says the error occurs in the spotify_api.py file in line 74 when executing _check_response function.

I had no time for further debugging so far.

**Comment by vijaykrpp** [comment] 2024-08-23 05:58
looks like good days are over. Spotify caught us and they are refuding to serve the requests thru this library, giving 403 forbidden errors.

**Comment by cisko99za** [comment] 2024-08-23 14:59
yep, from some days download failed ...

**Comment by glomatico** [comment] 2024-08-24 18:11
Duplicate of #66

**Closed by glomatico** 2024-08-24 18:11 UTC
