### ISSUE TITLE
fail again in download

### ISSUE THREAD

**Issue by phwaleed2024** [glomatico/spotify-web-downloader#78] opened 2024-09-12 00:20 UTC
i got error again in downloading any song
[
![Screenshot (7)](https://github.com/user-attachments/assets/e6ee49fb-4669-42d8-813b-883a92f720d8)
](url)

**Comment by glomatico** [comment] 2024-09-12 01:02
Duplicate of #70

**Closed by glomatico** 2024-09-12 01:02 UTC

**Comment by phwaleed2024** [comment] 2024-09-12 01:21
i made the update as the last time but still fails

**Comment by phwaleed2024** [comment] 2024-09-12 02:05
i run that
pip install -U spotify-web-downloader
but the same error i get
