### ISSUE TITLE
Suspicious Error

### ISSUE THREAD

**Issue by zoligamer** [glomatico/spotify-web-downloader#77] opened 2024-09-10 16:19 UTC
spotify-web-downloader "https://open.spotify.com/track/64WcVtoABTObpWvdAYtJll?si=555812d815ae4765"
[WARNING  18:18:01] Free account detected, lyrics will not be downloaded
[INFO     18:18:02] (Track 1/1 from URL 1/1) Downloading "Amit a vér kíván"
[ERROR    18:18:02] (Track 1/1 from URL 1/1) Failed to download "Amit a vér kíván"
[INFO     18:18:02] Done (1 error(s))

where to look for any log files, what is the problem?

(EDIT)
I used --print-exceptions tag, and got this:
[WARNING  18:24:33] Free account detected, lyrics will not be downloaded
[INFO     18:24:33] (Track 1/1 from URL 1/1) Downloading "Amit a vér kíván"
[ERROR    18:24:33] (Track 1/1 from URL 1/1) Failed to download "Amit a vér kíván"
Traceback (most recent call last):
  File "C:\Users\Zozi\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 72, in _check_response
    response.raise_for_status()
  File "C:\Users\Zozi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zozi\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_web_downloader\cli.py", line 468, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zozi\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_web_downloader\downloader_song.py", line 69, in get_decryption_key
    license = self.downloader.spotify_api.get_widevine_license_music(challenge)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zozi\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 101, in get_widevine_license_music
    self._check_response(response)
  File "C:\Users\Zozi\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 74, in _check_response
    raise Exception(
Exception: Request failed with status code 403:
[INFO     18:24:33] Done (1 error(s))

**Comment by glomatico** [comment] 2024-09-10 17:00
You are running and old version. Update with pip:
```bash
pip install -U spotify-web-downloader
```
Also, duplicate of #70

**Closed by glomatico** 2024-09-10 17:00 UTC
